### ISSUE TITLE
webserver2.js Counter

### ISSUE THREAD

**Issue by ghost** [hectorcorrea/intro-to-nodejs#2]
Hello,

I just recently read about how to use `Node.js`, looking over one of your blogs in an attempt to get the gist of it. So I went ahead and took a look at some of the code in this repo and I was wondering why there was a counter in `webserver2.js`. Based on what I saw, 

>   counter++;
>   console.log("Request: " + req.url + " (" + counter + ")");

it seemed like this would only cause spam because who knows how long it would be until a user actually sends a request to the server. Maybe I'm wrong about this, but I'm just curious.

**Comment by hectorcorrea** [comment]
The counter is there just to help see on the terminal/console that a new request has been processed. A production version of this would probably show the date and time of the request instead.
